# Configure API keys
GOOGLE_API_KEY = "YOUR_GOOGLE_API_KEY"
ANTHROPIC_API_KEY = "YOUR_ANTHROPIC_API_KEY"
LLAMA_API_KEY = "YOUR_LLAMA_API_KEY"
GROK_API_KEY = "YOUR_GROK_API_KEY"
DEEPSEEK_API_KEY = "YOUR_DEEPSEEK_API_KEY"
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"